-- Play feedback data for play_user (play@test.com). Run with:
--   npx wrangler d1 execute data --local --file scripts/test-feedback.sql
-- Then log in as play@test.com and visit /feedback/view.

DELETE FROM feedback WHERE id LIKE 'fb_%';

-- Mid-quarter (10 rows, varied AGREEMENT responses)
INSERT INTO feedback (id, recipientId, feedback) VALUES
('fb_mq_1','play_user','{"feedback_type":"mid_quarter","activities":["discussion"],"hours":"3","mq_approachable":"strongly_agree","mq_helpful":"strongly_agree","mq_familiar":"agree","mq_engagement":"agree","mq_questioning":"agree","mq_supportive":"strongly_agree","mq_name":"agree","mq_belonging":"strongly_agree","mq_checkin":"agree","mq_small_groups":"strongly_agree","mq_strengths":"Very patient.","mq_improve":"Keep going!"}'),
('fb_mq_2','play_user','{"feedback_type":"mid_quarter","activities":["discussion","office_hours"],"hours":"4","mq_approachable":"strongly_agree","mq_helpful":"agree","mq_familiar":"strongly_agree","mq_engagement":"agree","mq_questioning":"strongly_agree","mq_supportive":"agree","mq_name":"disagree","mq_belonging":"agree","mq_checkin":"strongly_agree","mq_small_groups":"agree","mq_strengths":"Great explanations.","mq_improve":"Learn names."}'),
('fb_mq_3','play_user','{"feedback_type":"mid_quarter","activities":["discussion"],"hours":"2","mq_approachable":"agree","mq_helpful":"agree","mq_familiar":"agree","mq_engagement":"disagree","mq_questioning":"disagree","mq_supportive":"agree","mq_name":"na","mq_belonging":"agree","mq_checkin":"agree","mq_small_groups":"strongly_agree","mq_strengths":"Friendly.","mq_improve":"More group work."}'),
('fb_mq_4','play_user','{"feedback_type":"mid_quarter","activities":["discussion"],"hours":"3","mq_approachable":"strongly_agree","mq_helpful":"strongly_agree","mq_familiar":"strongly_agree","mq_engagement":"strongly_agree","mq_questioning":"agree","mq_supportive":"strongly_agree","mq_name":"strongly_agree","mq_belonging":"strongly_agree","mq_checkin":"strongly_agree","mq_small_groups":"strongly_agree","mq_strengths":"Excellent all around.","mq_improve":"Nothing."}'),
('fb_mq_5','play_user','{"feedback_type":"mid_quarter","activities":["lecture","discussion"],"hours":"5","mq_approachable":"agree","mq_helpful":"strongly_disagree","mq_familiar":"disagree","mq_engagement":"disagree","mq_questioning":"strongly_disagree","mq_supportive":"disagree","mq_name":"disagree","mq_belonging":"disagree","mq_checkin":"disagree","mq_small_groups":"agree","mq_strengths":"Tries.","mq_improve":"Be more prepared."}'),
('fb_mq_6','play_user','{"feedback_type":"mid_quarter","activities":["discussion","study_session"],"hours":"4","mq_approachable":"strongly_agree","mq_helpful":"strongly_agree","mq_familiar":"agree","mq_engagement":"strongly_agree","mq_questioning":"strongly_agree","mq_supportive":"strongly_agree","mq_name":"agree","mq_belonging":"strongly_agree","mq_checkin":"strongly_agree","mq_small_groups":"strongly_agree","mq_strengths":"Amazing!","mq_improve":"N/A"}'),
('fb_mq_7','play_user','{"feedback_type":"mid_quarter","activities":["discussion"],"hours":"3","mq_approachable":"agree","mq_helpful":"agree","mq_familiar":"na","mq_engagement":"agree","mq_questioning":"agree","mq_supportive":"agree","mq_name":"agree","mq_belonging":"na","mq_checkin":"agree","mq_small_groups":"agree","mq_strengths":"Solid.","mq_improve":"Small things."}'),
('fb_mq_8','play_user','{"feedback_type":"mid_quarter","activities":["discussion","office_hours"],"hours":"6","mq_approachable":"strongly_agree","mq_helpful":"strongly_agree","mq_familiar":"strongly_agree","mq_engagement":"agree","mq_questioning":"agree","mq_supportive":"strongly_agree","mq_name":"strongly_agree","mq_belonging":"agree","mq_checkin":"strongly_agree","mq_small_groups":"strongly_agree","mq_strengths":"Goes above and beyond.","mq_improve":"Nothing much."}'),
('fb_mq_9','play_user','{"feedback_type":"mid_quarter","activities":["discussion"],"hours":"2","mq_approachable":"disagree","mq_helpful":"disagree","mq_familiar":"agree","mq_engagement":"disagree","mq_questioning":"disagree","mq_supportive":"disagree","mq_name":"strongly_disagree","mq_belonging":"disagree","mq_checkin":"disagree","mq_small_groups":"agree","mq_strengths":"Knows material.","mq_improve":"Engage more."}'),
('fb_mq_10','play_user','{"feedback_type":"mid_quarter","activities":["discussion"],"hours":"3","mq_approachable":"strongly_agree","mq_helpful":"agree","mq_familiar":"agree","mq_engagement":"agree","mq_questioning":"strongly_agree","mq_supportive":"strongly_agree","mq_name":"agree","mq_belonging":"strongly_agree","mq_checkin":"agree","mq_small_groups":"strongly_agree","mq_strengths":"Encouraging.","mq_improve":"More examples."}');

-- End-of-quarter (6 rows)
INSERT INTO feedback (id, recipientId, feedback) VALUES
('fb_eq_1','play_user','{"feedback_type":"end_of_quarter","activities":["discussion"],"hours":"3","eq_approachable":"big_improvement","eq_helpful":"big_improvement","eq_familiar":"little_improvement","eq_engagement":"no_change","eq_questioning":"little_improvement","eq_supportive":"big_improvement","eq_name":"little_improvement","eq_belonging":"big_improvement","eq_notes":"Really grew this quarter."}'),
('fb_eq_2','play_user','{"feedback_type":"end_of_quarter","activities":["discussion"],"hours":"4","eq_approachable":"no_room_for_improvement","eq_helpful":"no_room_for_improvement","eq_familiar":"big_improvement","eq_engagement":"little_improvement","eq_questioning":"big_improvement","eq_supportive":"no_room_for_improvement","eq_name":"no_change","eq_belonging":"big_improvement","eq_notes":"Consistent."}'),
('fb_eq_3','play_user','{"feedback_type":"end_of_quarter","activities":["discussion","office_hours"],"hours":"5","eq_approachable":"big_improvement","eq_helpful":"little_improvement","eq_familiar":"no_change","eq_engagement":"no_change","eq_questioning":"no_change","eq_supportive":"little_improvement","eq_name":"na","eq_belonging":"little_improvement","eq_notes":"Modest growth."}'),
('fb_eq_4','play_user','{"feedback_type":"end_of_quarter","activities":["discussion"],"hours":"3","eq_approachable":"no_room_for_improvement","eq_helpful":"big_improvement","eq_familiar":"big_improvement","eq_engagement":"big_improvement","eq_questioning":"big_improvement","eq_supportive":"big_improvement","eq_name":"big_improvement","eq_belonging":"no_room_for_improvement","eq_notes":"Huge improvement."}'),
('fb_eq_5','play_user','{"feedback_type":"end_of_quarter","activities":["discussion"],"hours":"2","eq_approachable":"little_improvement","eq_helpful":"little_improvement","eq_familiar":"little_improvement","eq_engagement":"little_improvement","eq_questioning":"no_change","eq_supportive":"little_improvement","eq_name":"no_change","eq_belonging":"little_improvement","eq_notes":"Some progress."}'),
('fb_eq_6','play_user','{"feedback_type":"end_of_quarter","activities":["discussion","study_session"],"hours":"4","eq_approachable":"big_improvement","eq_helpful":"big_improvement","eq_familiar":"big_improvement","eq_engagement":"big_improvement","eq_questioning":"little_improvement","eq_supportive":"big_improvement","eq_name":"little_improvement","eq_belonging":"big_improvement","eq_notes":"Great quarter."}');

-- LA Observation (5 rows)
INSERT INTO feedback (id, recipientId, feedback) VALUES
('fb_ob_1','play_user','{"feedback_type":"la_observation","obs_approachable":"always","obs_engaging":"most_instructor","obs_questioning":"sometimes","obs_checkin":"most_missed","obs_supportive":"always","obs_name":"sometimes","obs_belonging":"most_instructor","obs_small_groups":"always","obs_wait_time":"most_missed","obs_equity":"most_instructor","obs_prompt":"always","obs_strengths":"Warm.","obs_improve":"Wait longer.","obs_notes":"Nice session."}'),
('fb_ob_2','play_user','{"feedback_type":"la_observation","obs_approachable":"most_instructor","obs_engaging":"always","obs_questioning":"most_instructor","obs_checkin":"most_instructor","obs_supportive":"always","obs_name":"most_missed","obs_belonging":"always","obs_small_groups":"always","obs_wait_time":"sometimes","obs_equity":"always","obs_prompt":"most_instructor","obs_strengths":"Great energy.","obs_improve":"Use names.","obs_notes":""}'),
('fb_ob_3','play_user','{"feedback_type":"la_observation","obs_approachable":"always","obs_engaging":"most_missed","obs_questioning":"almost_never","obs_checkin":"sometimes","obs_supportive":"most_instructor","obs_name":"almost_never","obs_belonging":"sometimes","obs_small_groups":"most_instructor","obs_wait_time":"almost_never","obs_equity":"sometimes","obs_prompt":"sometimes","obs_strengths":"Kind.","obs_improve":"Ask more questions.","obs_notes":""}'),
('fb_ob_4','play_user','{"feedback_type":"la_observation","obs_approachable":"always","obs_engaging":"always","obs_questioning":"always","obs_checkin":"always","obs_supportive":"always","obs_name":"most_instructor","obs_belonging":"always","obs_small_groups":"always","obs_wait_time":"most_instructor","obs_equity":"always","obs_prompt":"always","obs_strengths":"Exemplary.","obs_improve":"None.","obs_notes":"Model observation."}'),
('fb_ob_5','play_user','{"feedback_type":"la_observation","obs_approachable":"most_instructor","obs_engaging":"sometimes","obs_questioning":"most_missed","obs_checkin":"sometimes","obs_supportive":"most_instructor","obs_name":"sometimes","obs_belonging":"most_instructor","obs_small_groups":"most_instructor","obs_wait_time":"sometimes","obs_equity":"most_instructor","obs_prompt":"most_instructor","obs_strengths":"Organized.","obs_improve":"Push deeper.","obs_notes":""}');

-- TA feedback (4 rows)
INSERT INTO feedback (id, recipientId, feedback) VALUES
('fb_ta_1','play_user','{"role":"ta","ta_prepared":"strongly_agree","ta_engaged":"agree","ta_professional":"strongly_agree","ta_communication":"agree","ta_questions":"agree","ta_group_work":"strongly_agree","ta_equity":"agree","ta_feedback":"strongly_agree","ta_reliable":"strongly_agree","ta_growth":"agree","ta_strengths":"Great teammate.","ta_improve":"Nothing.","ta_notes":""}'),
('fb_ta_2','play_user','{"role":"ta","ta_prepared":"agree","ta_engaged":"strongly_agree","ta_professional":"strongly_agree","ta_communication":"strongly_agree","ta_questions":"strongly_agree","ta_group_work":"agree","ta_equity":"strongly_agree","ta_feedback":"agree","ta_reliable":"strongly_agree","ta_growth":"strongly_agree","ta_strengths":"Attentive.","ta_improve":"None.","ta_notes":""}'),
('fb_ta_3','play_user','{"role":"ta","ta_prepared":"disagree","ta_engaged":"agree","ta_professional":"agree","ta_communication":"disagree","ta_questions":"agree","ta_group_work":"agree","ta_equity":"agree","ta_feedback":"disagree","ta_reliable":"agree","ta_growth":"agree","ta_strengths":"Shows up.","ta_improve":"Prep more.","ta_notes":""}'),
('fb_ta_4','play_user','{"role":"ta","ta_prepared":"strongly_agree","ta_engaged":"strongly_agree","ta_professional":"strongly_agree","ta_communication":"strongly_agree","ta_questions":"strongly_agree","ta_group_work":"strongly_agree","ta_equity":"strongly_agree","ta_feedback":"strongly_agree","ta_reliable":"strongly_agree","ta_growth":"strongly_agree","ta_strengths":"Top tier.","ta_improve":"Nothing.","ta_notes":""}');
